# Generated by Django 4.0.6 on 2022-07-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InnovationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('in_cgiar_innovation_dashboard', models.CharField(choices=[('yes', 'Yes, provide the CGIAR Innovation Dashboard ID or Title of Innovation as answer to the next question'), ('yes_no_id', 'Yes, but I cannot find the Innovation ID or Title of Innovation in the CGIAR Innovation Dashboard'), ('i_dnt_know', 'I do not know'), ('no', 'No, this innovation is not documented in the existing CGIAR Innovation Dashboard')], max_length=50)),
                ('innovation_dashboard_id_or_title', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
