# Generated by Django 4.0.6 on 2022-07-10 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnovationReferenceMaterialUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(null=True)),
                ('url', models.URLField()),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.innovationprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InnovationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(null=True)),
                ('image', models.ImageField(upload_to='innovationprofiles')),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.innovationprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
