# Generated by Django 4.0.6 on 2022-07-10 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_innovationprofile_characterization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnovationContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contributor_order', models.IntegerField(default=0)),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.innovationprofile')),
            ],
            options={
                'ordering': ['contributor_order'],
            },
        ),
        migrations.CreateModel(
            name='InnovationContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.innovationprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
